// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview7-19363-02")]
    public sealed partial class AddMembershipTypeName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMembershipTypeName));
        
        string IMigrationMetadata.Id
        {
            get { return "201907310409363_AddMembershipTypeName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
